//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCSI.Payroll.DatabaseConception
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialContributionEmployer
    {
        public int Id { get; set; }
        public decimal RRQ_RATE { get; set; }
        public decimal RRQ_MGA { get; set; }
        public decimal Employment_Insurance { get; set; }
        public decimal RQAP_RATE { get; set; }
        public decimal MQAP_MGA { get; set; }
        public decimal CNESST { get; set; }
        public decimal FSS { get; set; }
        public decimal FDRCMO { get; set; }
        public int FiscalYearId { get; set; }
    
        public virtual FiscalYear FiscalYear { get; set; }
    }
}
