//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCSI.Payroll.DatabaseConception
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxBracket
    {
        public int Id { get; set; }
        public decimal LowerLimit { get; set; }
        public decimal UpperLimit { get; set; }
        public decimal Rate { get; set; }
        public int FiscalYearId { get; set; }
        public int GovernmentId { get; set; }
    
        public virtual FiscalYear FiscalYear { get; set; }
        public virtual Government Government { get; set; }
    }
}
